trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingsystem: ubuntu-latest
#     mac:
#       operatingsystem: macos-latest
 
pool:
  vmImage: $(operatingsystem)

stages:
 - stage: Build
   jobs:
     - job: BuildJob
       steps:
         - bash: echo Build Step!!! 
 - stage: DevDeploy
   jobs:
     - deployment: DevDeployJob
       strategy:
         runOnce:
           deploy:
            steps:
              - script: echo Deploying to DEV
 
 - stage: QADeploy
   jobs:
     - deployment: QADeployJob
       strategy:
         runOnce:
           deploy:
            steps:
              - script: echo Deploying to QA
# steps:
# - script: echo Running on $(operatingsystem)!
#   displayName: 'Run a one-line script'